#!/usr/bin/env bash
#
display_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$(dig $subdomain.$domain +short)
    local destination_ip=$(dig $subdomain.$domain +short)

    echo "The subdomain $subdomain is a $record_type record and points to $destination_ip"
}

if [ "$#" -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"; do
        display_info $1 $sub_domain
    done
elif [ "$#" -eq 2 ]; then
    display_info $1 $2
else
    echo "Usage: $0 <domain> [subdomain]"
fi

